import type { NextPage } from 'next'
import Head from 'next/head'
import { fetchCharacters } from "../utils/api";
import { Header } from "../components/header";
import Footer from "../components/footer";
import { useState } from "react";
import Carousel from "../components/carousel";

const Home: NextPage<{}> = () => {
  const [currentIndex, setCurrentIndex] = useState(0);

  const handlePrev = () => {
    setCurrentIndex((prevIndex) => (prevIndex > 0 ? prevIndex - 1 : 0));
  };

  const handleNext = () => {
    setCurrentIndex((prevIndex) =>
      prevIndex < dummyCharacters.length - 3 ? prevIndex + 1 : prevIndex
    );
  };
  const dummyCharacters = [
    {
      id: "9e3f7ce4-b9a7-4244-b709-dae5c1f1d4a8",
      name: "Harry Potter",
      alternate_names: ["The Boy Who Lived", "The Chosen One"],
      species: "human",
      gender: "male",
      house: "Gryffindor",
      dateOfBirth: "31-07-1980",
      yearOfBirth: 1980,
      wizard: true,
      ancestry: "half-blood",
      eyeColour: "green",
      hairColour: "black",
      wand: { wood: "holly", core: "phoenix feather", length: 11 },
      patronus: "stag",
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: "Daniel Radcliffe",
      alternate_actors: [],
      alive: true,
      image: "https://ik.imagekit.io/hpapi/harry.jpg",
    },
    {
      id: "4c7e6819-a91a-45b2-a454-f931e4a7cce3",
      name: "Hermione Granger",
      alternate_names: [],
      species: "human",
      gender: "female",
      house: "Gryffindor",
      dateOfBirth: "19-09-1979",
      yearOfBirth: 1979,
      wizard: true,
      ancestry: "muggleborn",
      eyeColour: "brown",
      hairColour: "brown",
      wand: { wood: "vine", core: "dragon heartstring", length: 10.75 },
      patronus: "otter",
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: "Emma Watson",
      alternate_actors: [],
      alive: true,
      image: "https://ik.imagekit.io/hpapi/hermione.jpeg",
    },
    {
      id: "c3b1f9a5-b87b-48bf-b00d-95b093ea6390",
      name: "Ron Weasley",
      alternate_names: ["Dragomir Despard"],
      species: "human",
      gender: "male",
      house: "Gryffindor",
      dateOfBirth: "01-03-1980",
      yearOfBirth: 1980,
      wizard: true,
      ancestry: "pure-blood",
      eyeColour: "blue",
      hairColour: "red",
      wand: { wood: "willow", core: "unicorn tail-hair", length: 14 },
      patronus: "Jack Russell terrier",
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: "Rupert Grint",
      alternate_actors: [],
      alive: true,
      image: "https://ik.imagekit.io/hpapi/ron.jpg",
    },
    {
      id: "af95bd8a-dfae-45bb-bc69-533860d34129",
      name: "Draco Malfoy",
      alternate_names: [],
      species: "human",
      gender: "male",
      house: "Slytherin",
      dateOfBirth: "05-06-1980",
      yearOfBirth: 1980,
      wizard: true,
      ancestry: "pure-blood",
      eyeColour: "grey",
      hairColour: "blonde",
      wand: { wood: "hawthorn", core: "unicorn tail-hair", length: 10 },
      patronus: "",
      hogwartsStudent: true,
      hogwartsStaff: false,
      actor: "Tom Felton",
      alternate_actors: [],
      alive: true,
      image: "https://ik.imagekit.io/hpapi/draco.jpg",
    },
    {
      id: "ca3827f0-375a-4891-aaa5-f5e8a5bad225",
      name: "Minerva McGonagall",
      alternate_names: [],
      species: "human",
      gender: "female",
      house: "Gryffindor",
      dateOfBirth: "04-10-1925",
      yearOfBirth: 1925,
      wizard: true,
      ancestry: "half-blood",
      eyeColour: "",
      hairColour: "black",
      wand: { wood: "fir", core: "dragon heartstring", length: 9.5 },
      patronus: "tabby cat",
      hogwartsStudent: false,
      hogwartsStaff: true,
      actor: "Dame Maggie Smith",
      alternate_actors: [],
      alive: true,
      image: "https://ik.imagekit.io/hpapi/mcgonagall.jpg",
    },
  ];

  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
      <Head>
        <title>Harry Potter App</title>
        <meta name="description" content="Generated by Cypherfelix" />
        <link rel="icon" href="/" />
      </Head>

      <Header />

      <Carousel items={dummyCharacters.slice(0, 5)} />

      <Footer />
    </div>
  );
};

export const getServerSideProps = async () => {
  const characters = await fetchCharacters();
  console.log(characters.slice(0, 5));
  return {
    props: { characters },
  };
};


export default Home
