import type { NextPage } from 'next'
import Head from 'next/head'
import { fetchCharacters } from "../utils/api";
import { Header } from "../components/header";
import Footer from "../components/footer";

const Home: NextPage<{}> = () => {
  return (
    <div className="flex flex-col min-h-screen bg-gray-100 dark:bg-gray-900">
      <Head>
        <title>Harry Potter App</title>
        <meta name="description" content="Generated by Cypherfelix" />
        <link rel="icon" href="/" />
      </Head>

      <Header />

      <Footer />
    </div>
  );
};

export const getServerSideProps = async () => {
  const characters = await fetchCharacters();
  console.log(characters.slice(0, 5));
  return {
    props: { characters },
  };
};


export default Home
