import type { NextPage } from 'next'
import Head from 'next/head'
import { fetchCharacters } from "../utils/api";

const Home: NextPage = () => {
  return (
    <div className={`px-0 py-2`}>
      <Head>
        <title>Harry Potter App</title>
        <meta name="description" content="Generated by Cypherfelix" />
        <link rel="icon" href="/" />
      </Head>

      <h1 className='text-center text-3xl text-blue-500' > Welcome </h1>

    </div>
  )
}

export const getServerSideProps = async () => {
  const characters = await fetchCharacters();
  console.log(characters);
  return {
    props: { characters },
  };
};


export default Home
